POST http://localhost:4100/users
Content-Type: application/json

{
    "name": "Sheila Nyambura",
    "email": "sheila@yopmail.com",
    "phone_number": "0712345634",
    "role": "customer",
    "password": "12345678",
    "profile_image": "",
    "location": "Nyeri"
}

### GETTING ALL USERS

GET http://localhost:4100/users
Content-Type: application/json


### GETTING USER BY ID

GET http://localhost:4100/users/4756cf7d-ff5c-4b78-965d-864691cbe560


###
PUT http://localhost:4100/users/update/4756cf7d-ff5c-4b78-965d-864691cbe560
Content-Type: application/json

{
    "name": "Nyambura Chomba",
    "email": "sheila@yopmail.com",
    "phone_number": "0787654321",
    "role": "customer",
    "password": "12345678",
    "profile_image": ""
}

###

DELETE http://localhost:4100/users/delete/0b525987-47df-43ee-85a6-ab856849313b
Content-Type: application/json