POST http://localhost:4100/users
Content-Type: application/json

{
    "name": "James Kariuki",
    "email": "jamesew2605@gmail.com",
    "phone_number": "0798678330",
    "role": "driver",
    "password": "12345678",
    "profile_image": "https://cdn.pixabay.com/photo/2016/08/31/11/54/icon-1633249_640.png",
    "location": "Nairobi"
}

### GETTING ALL USERS

GET http://localhost:4100/users
Content-Type: application/json


### GETTING USER BY ID

GET http://localhost:4100/users/4756cf7d-ff5c-4b78-965d-864691cbe560


###
PUT http://localhost:4100/users/update/4756cf7d-ff5c-4b78-965d-864691cbe560
Content-Type: application/json

{
    "name": "Nyambura Chomba",
    "email": "sheila@yopmail.com",
    "phone_number": "0787654321",
    "role": "customer",
    "password": "12345678",
    "profile_image": ""
}

###

DELETE http://localhost:4100/users/delete/0b525987-47df-43ee-85a6-ab856849313b
Content-Type: application/json