POST http://localhost:4100/auth/login
Content-Type: application/json

{
    "email": "jamesew2605@gmail.com",
    "password": "12345678"
}

####
PUT http://localhost:4100/auth/reset_pwd
Content-Type: application/json

{
    "email": "meshackkorir100@gmail.com",
    "phone_number": "0198678330",
    "password": "12345678"
}

####
GET http://localhost:4100/auth/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJkZjU3ZTQtZjJkNy00ZGRkLTg5OGMtMDIyZjkxNTgyMTEzIiwibmFtZSI6IkphbWVzIEthcml1a2kiLCJlbWFpbCI6ImphbWVzZXcyNjA1QGdtYWlsLmNvbSIsInJvbGUiOiJkcml2ZXIiLCJpYXQiOjE3MDg1ODU3MjQsImV4cCI6MTcwODU4OTMyNH0.fTGLnf_bv9qRAhMhmPRGmfnSw-e9dAFUZ9hMk08YLfo