POST http://localhost:4100/auth/login
Content-Type: application/json

{
    "email": "jamesew2605@gmail.com",
    "password": "12345678"
}

####
PUT http://localhost:4100/auth/reset_pwd
Content-Type: application/json

{
    "email": "meshackkorir100@gmail.com",
    "phone_number": "0198678330",
    "password": "12345678"
}

####
GET http://localhost:4100/auth/checkdetails
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjJkZjU3ZTQtZjJkNy00ZGRkLTg5OGMtMDIyZjkxNTgyMTEzIiwibmFtZSI6IkphbWVzIEthcml1a2kiLCJlbWFpbCI6ImphbWVzZXcyNjA1QGdtYWlsLmNvbSIsInJvbGUiOiJkcml2ZXIiLCJpYXQiOjE3MDg1OTU4OTAsImV4cCI6MTcwODU5OTQ5MH0.scV_-DxwrDFrJWvq6_J5YGW_Jm6feEEUeJa4hmR1AZk