POST http://localhost:4100/trips/order_rhide
Content-Type: application/json

{
    "customer_id": "206ff9b5-5413-4f20-b343-501285fcf0a3",
    "driver_id": "1d1502e4-25ac-46de-90ad-c89554f29daf",
    "where_from": "Kamakwa",
    "destination": "Gatitu",
    "price": "1000 KSH",
    "vehicle_size": "SM"
}

###GET MY RIDES
GET http://localhost:4100/trips/1d1502e4-25ac-46de-90ad-c89554f29daf
Content-Type: application/json