POST http://localhost:4100/trips/order_rhide
Content-Type: application/json

{
    "customer_id": "4756cf7d-ff5c-4b78-965d-864691cbe560",
    "driver_id": "62df57e4-f2d7-4ddd-898c-022f91582113",
    "where_from": "Nyeri",
    "destination": "Nanyuki",
    "price": "1500 KSH",
    "vehicle_size": "SM"
}

###GET CUSTOMER RIDES 
GET http://localhost:4100/trips/customer/4756cf7d-ff5c-4b78-965d-864691cbe560
Content-Type: application/json


###GET DRIVER RIDES
GET http://localhost:4100/trips/driver/62df57e4-f2d7-4ddd-898c-022f91582113
Content-Type: application/json